name: Deploy to Firebase Hosting on merge

on:
  push:
    branches:
      - main  # Change to the branch you’re working on, e.g., `master`

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'
    
    - name: Install Dependencies
      run: npm install
    
    - name: Build
      run: npm run build
    
    - name: Deploy to Firebase Hosting
      uses: FirebaseExtended/action-hosting-deploy@v0
      with:
        repoToken: '${{ secrets.GITHUB_TOKEN }}'
        firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_PAWPETS_A77FA }}'
        channelId: live
        projectId: your-firebase-project-id  # Replace with your Firebase project ID
